trigger:
  branches:
    include:
      - '*'

pool:
  name: 'Default' # Tu máquina local como servidor

steps:
- checkout: self
  persistCredentials: true
  clean: true
  fetchDepth: 0

- powershell: |
    # Configura la identidad de Git
    git config --global user.email "azuredevops@microsoft.com"
    git config --global user.name "Azure DevOps Pipeline"
    
    Write-Host "Iniciando sincronizacion limpia con GitHub usando PowerShell..."
    
    # En PowerShell ejecutamos el comando directo. Las comillas simples protegen toda la cadena de Git
    git push --prune "https://github.com/jescorcia18/TFE_AgroVisionPWA" '+refs/remotes/origin/*:refs/heads/*' '+refs/tags/*:refs/tags/*'
  displayName: 'Hacer espejo hacia GitHub'